services:
  # MySQL数据库服务
  db:
    image: mysql:8.0
    container_name: aiturbo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aiturbo
      MYSQL_USER: aiturbo_user
      MYSQL_PASSWORD: aiturbo_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # AITurbo应用服务
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aiturbo_app
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=aiturbo_user
      - DB_PASSWORD=aiturbo_password
      - DB_NAME=aiturbo
      - DOCKER_ENV=true
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: >
      sh -c "
        echo '等待数据库启动...' &&
        sleep 15 &&
        python init_database_docker.py &&
        gunicorn --bind 0.0.0.0:5000 --workers 2 --worker-class sync --timeout 300 app_new:app
      "

volumes:
  db_data: